### ISSUE TITLE
Snippets?

### ISSUE THREAD

**Issue by john-hillert** [edgardmessias/vscode.clipboard-manager#113]
Hi, I do not know why VS Code marketplace sends us here for Q&A about an extension, but here is where I will ask.  Can you explain what "snippets" is referring to in the description of the extension, and how to use the feature?

**Comment by edgardmessias** [comment]
It is simple, just type `clip1` and press enter to paste the last clipboard history, `clip2` to second, ....

**Comment by edgardmessias** [comment]
You can ajust following configs:
```js
  // Maximum number of clips to suggests in snippets (Zero for all)
  "clipboard-manager.snippet.max": 10,

  // Default prefix for snippets completion (clip1, clip2, ...)
  "clipboard-manager.snippet.prefix": "clip"
```
