### ISSUE TITLE
Saving history

### ISSUE THREAD

**Issue by richburdon** [edgardmessias/vscode.clipboard-manager#24]
For presentations it would be really useful to be able to save the clipboard state and reload it.

I realize this is a niche feature, but perhaps in settings it would be simple to configure a file where the state is read/written rather than this being in memory?

**Comment by edgardmessias** [comment]
See https://github.com/edgardmessias/vscode.clipboard-manager/blob/1d6f040aa44d5fa756d6d79a81f85dbceaa5cd64/src/manager.ts#L173
