### ISSUE TITLE
set the path to the clipboard history json file

### ISSUE THREAD

**Issue by shelper** [edgardmessias/vscode.clipboard-manager#25]
let the user to decide where to save the clipboard history. 

saving it to the default folder causes un-necessary version control of clipboard history when working with extension ` sync setting `

**Comment by jaredreynolds** [comment]
Workaround:  Add `clipboard.history.json` to the list of ignored files in Setting Sync's [global settings](https://github.com/shanalikhan/code-settings-sync#global-settings).  See that link for the location of your file then change it like so:

```
{
    "ignoreUploadFiles": [
        ...
        "clipboard.history.json"
    ],
    ...
}
```
