### ISSUE TITLE
Preview the paste feature accumulates text from all paste options

### ISSUE THREAD

**Issue by cvzakharchenko** [edgardmessias/vscode.clipboard-manager#255]
The bug appeared on a recent VSCode update.
When cycling through paste options the preview instead of replacing one option with another accumulates all options and paste them all at once.
This made preview completely broken.

https://user-images.githubusercontent.com/6278349/218450842-1dc5251e-9a0b-4d2f-a0a1-45057f5f6c01.mp4

**Comment by sadovsf** [comment]
Same issue on Mac. Seems to be related to some recent VSCode update. Is repo still alive?

**Comment by drackp2m** [comment]
> Same issue on Mac. Seems to be related to some recent VSCode update. Is repo still alive?

Last commit 2021 Jan... :(

Same problem on macOS and Ubuntu.

**Comment by joyous-coder** [comment]
Please fix this

**Comment by azhiv** [comment]
@edgardmessias Could you please review this [PR](https://github.com/edgardmessias/vscode.clipboard-manager/pull/256) with a fix for that issue?

**Comment by edgardmessias** [comment]
Hi, thanks @azhiv , I look your PR and try to release the fix

**Comment by azhiv** [comment]
@edgardmessias Thank you for taking the action so quickly! Do you have an ETA for the fresh release of the extension?

**Comment by edgardmessias** [comment]
@azhiv done

**Comment by azhiv** [comment]
Great work!

**Comment by svivian** [comment]
Hi, when does this get released? I've restarted, checked for updates etc but it's still on v1.4.2 (last updated 2020).

**Comment by xavier-villelegier** [comment]
Hey @edgardmessias, by any chance could you release the v1.5 please ? 🙏  The extension can't be used as it is 😔

**Comment by edgardmessias** [comment]
@xavier-villelegier , done
