### ISSUE TITLE
shortcut key to clipboard only

### ISSUE THREAD

**Issue by JipingWang** [edgardmessias/vscode.clipboard-manager#26]
does anyone feel it's overwhelming coping everything to the Clipboard-Manager list?

Wouldn't it be nice just explicitly copy to the list when Ctrl+Shift+C?

**Comment by edgardmessias** [comment]
Hello @JipingWang , I added the option to use a shortcut key to copy to clipboard history.
You can set "clipboard-manager.checkInterval" to zero to disable automatic history
