### ISSUE TITLE
Can we use command instead of control in Macos?

### ISSUE THREAD

**Issue by khushal123** [edgardmessias/vscode.clipboard-manager#27]

**Comment by edgardmessias** [comment]
You can use the keybindings:
```js
[
// ...
    {
        "command": "clipboard-manager.editor.pickAndPaste",
        "key": "Ctrl+Shift+V",
        "when": "textInputFocus && !editorReadonly"
    }
// ...
]
```

**Comment by khushal123** [comment]
Not working

**Comment by khushal123** [comment]
Instead of ctrl + shift + v can I use command + shift+v I meant

**Comment by edgardmessias** [comment]
Sorry, the key is: `Cmd+Shift+V`

**Comment by khushal123** [comment]
no it does not work with cmd in mac it works with control,,,,

**Comment by edgardmessias** [comment]
Try remove the `when` clause

**Comment by cpsauer** [comment]
Rebinding the keys works, but it'd be sweet if it used Cmd on mac out of the box. @edgardmessias, is that something you'd be willing to add? 

Thanks for building such a useful extension!

**Comment by cpsauer** [comment]
You're the best! Thank you.

**Comment by edgardmessias** [comment]
I will fix somethings and after that I will make a new release
