### ISSUE TITLE
Make it work in the commit message input field

### ISSUE THREAD

**Issue by lackovic** [edgardmessias/vscode.clipboard-manager#39]
Feature suggestion:
- make it work in the commit message input field.

**Comment by edgardmessias** [comment]
It is not possible at moment, but you can try use this: https://ditto-cp.sourceforge.io/

**Comment by lackovic** [comment]
@edgardmessias thanks! I just found out pasting from the clipboard history is [supported natively in Windows 10 since May 2018](https://blogs.windows.com/windowsexperience/2018/05/09/announcing-windows-10-insider-preview-build-17666/). You can also pin the items you find yourself using all the time.
