### ISSUE TITLE
Did this Extension will collect system level clipboard history?

### ISSUE THREAD

**Issue by QGB** [edgardmessias/vscode.clipboard-manager#40]
or is only for VSCode?

**Comment by edgardmessias** [comment]
It is a options `clipboard-manager.onlyWindowFocused`, if you set `false`, the extension can collect system level.

**Comment by QGB** [comment]
@edgardmessias   in VSCode remote-ssh ,it seems useless..

**Comment by edgardmessias** [comment]
I will check

> @edgardmessias no VSCode remote-ssh, parece inútil ..
