### ISSUE TITLE
can't get it to work on linux

### ISSUE THREAD

**Issue by reharik** [edgardmessias/vscode.clipboard-manager#41]
Hi, this probably isn't really an issue with the software.  I think I either have some messed up setting somewhere or a conflict or something, but I can't get clipboard manager to work. i.e. ctrl + shft + v does nothing.  I'm not sure how to diagnose the problem.  Perhaps if you could point me to what file the settings are added to, what settings you expect to change when once it's installed, potential setting conflicts you've heard of.  This would be super helpful.
Thank you,
Raif

**Comment by edgardmessias** [comment]
Hi, try install the package `xsel`

**Comment by reharik** [comment]
Hi, I'm sorry I"m not sure what you mean.

**Comment by edgardmessias** [comment]
Check in your linux distro and try install the package xsel
Like: apt install xsel (ubuntu)
yum install xsel (fedora, centos)

**Comment by reharik** [comment]
Oh, I see.  Yes I will try that.  Unfortunately I am now on my mac, working on ios crap.  But soon as I'm back to my comfortable linux box I'll try that. 
Is that a pre-requisite for your extension?

**Comment by edgardmessias** [comment]
No, my extension try use the native resource of VSCode, but not working with WSL or remote SSH.
The extension try use the embemed xsel, but some times not work

**Comment by reharik** [comment]
Hi, so I installed the xsel package, uninstalled clipboard-manager, then reinstalled clipboard-manager and still no action on ctrl shift v.   I think there may be a settings conflict. If you could let me know what settings are expected after the install and where they reside, if not in settings e.g. keyboard-bindings, I could check those and rule that out.
Thanks,
Raif

**Comment by reharik** [comment]
So I got it working. I looked at the keyboard bindings for "ctrl shift v" there were two there for java ( which I do not code in ).  I checked the first one and the when criteria was "lang=java"  but the second binding had the wen set as "!readonly"  which meant that any file or area that was not read only was forced to use this binding.  Lame. So I killed them both and now all is good.
