### ISSUE TITLE
Disable autosuggestion snippets

### ISSUE THREAD

**Issue by werunom** [edgardmessias/vscode.clipboard-manager#6]
Hey! Thanks for this nice extension. Thought it would be better if there is an option to disable the clipboard contents being suggested as snippets. Although being suggested while typing is useful in certain scenarios (like coding in certain languages), this might be irritating while writing long texts (for instance, writing documents in latex or pandoc). For instance, in my case: I want the clipboard-manager to keep the history of copied texts; but I dont want them to be suggested when I am working (`clip1`, etc.)

So, if you can provide a way to disable this autosuggestion, it would be great.

**Comment by edgardmessias** [comment]
Thanks @werunom, I will working on this

**Comment by werunom** [comment]
Thanks!
